### ISSUE TITLE
Is this data raw data or post-processing?

### ISSUE THREAD

**Issue by KamiCalcium** [GestureMan/mHomeGes-dataset#1]
Hi,

Is this provided data the raw data or after REMOVING INTERFERENCE and other post-processing step?

**Comment by GestureMan** [comment]
The data provided is the raw data gathered from the mmWave radar chip. Hope this help^_^

**Comment by GestureMan** [comment]
> Hi,
> 
> Is this provided data the raw data or after REMOVING INTERFERENCE and other post-processing step?

The data provided is the raw data gathered from the mmWave radar chip. Hope this help^_^

**Comment by KamiCalcium** [comment]
> > Hi,
> > Is this provided data the raw data or after REMOVING INTERFERENCE and other post-processing step?
> 
> The data provided is the raw data gathered from the mmWave radar chip. Hope this help^_^

Hi, 

Thanks for replying.

I read about your paper and I'm really interested in it. Could you please share the author's email with me? Such that we can discuss the paper in detail..!

Thanks a lot!!

**Comment by GestureMan** [comment]
Hi, recieved your message two days ago but cannot find it here.
You can directly send me message via my email: fengxudi@163.com
Glad to help each other

**Comment by KamiCalcium** [comment]
> Hi, recieved your message two days ago but cannot find it here.
> You can directly send me message via my email: [fengxudi@163.com](mailto:fengxudi@163.com)
> Glad to help each other

Hi I sent an email to you! Thanks!
